### PR TITLE
HLSL: Possibility to represent variable in binary form

### PR DESCRIPTION
**Pull request by Dawid-Lorenz-Mobica**

### CODE REVIEW

**Comment by Dawid-Lorenz-Mobica** [comment]
Hi @Patryk-Jastrzebski-Mobica @lorna-mcneill-mobica @Grzegorz-Smagacz-Mobica @Krzysztof-Dmitruk-Mobica ,
please make CR :)

**Review by Patryk-Jastrzebski-Mobica — APPROVED** [review]
LGTM

**Comment by lorna-mcneill-mobica** [comment]
LGTM2

**Comment by Dawid-Lorenz-Mobica** [comment]
Close: Moved to KhronosGroup glslang: https://github.com/KhronosGroup/glslang/pull/3259

**Pull request closed without merging**
